export const SITE_LIST_REQUEST = "SITE_LIST_REQUEST"
export const SITE_LIST_SUCCESS = "SITE_LIST_SUCCESS"
export const SITE_LIST_FAIL = "SITE_LIST_FAIL"

export const SITE_DETAILS_REQUEST = "SITE_DETAILS_REQUEST"
export const SITE_DETAILS_SUCCESS = "SITE_DETAILS_SUCCESS"
export const SITE_DETAILS_FAIL = "SITE_DETAILS_FAIL"